package com.juanbermudez.desktopapp.Vista;

import com.juanbermudez.desktopapp.Controlador.CRUDOperation;
import com.juanbermudez.desktopapp.Modelo.Usuario;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 * @author juanb
 */
public class AdminPanel extends javax.swing.JFrame{
    
    Usuario usr;

    private ImageIcon imagen;
    private Icon icono;
    public AdminPanel(Usuario usr) {
        initComponents();
        this.usr = usr;
        mostrarDatosUsuarios();
        this.setLocationRelativeTo(this);
        this.pintarLogo(this.lblLogo, "logo.png");
        
    }
    class jPanelGradient extends JPanel{
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int w = getWidth();
            int h = getHeight();
            Color color1 = new Color(30,41,59);
            Color color2 = new Color(255,85,85);
            double angleDegrees = 0; 
            double angleRadians = Math.toRadians(angleDegrees);
            double length = Math.sqrt(Math.pow(w, 2) + Math.pow(h, 2)); 
            int startX = (int) (w / 2 - (length / 2) * Math.cos(angleRadians)); 
            int startY = (int) (h / 2 - (length / 2) * Math.sin(angleRadians)); 
            int endX = (int) (w / 2 + (length / 2) * Math.cos(angleRadians)); 
            int endY = (int) (h / 2 + (length / 2) * Math.sin(angleRadians)); 
            Point pt1 = new Point(startX, startY);
            Point pt2 = new Point(endX, endY);
            GradientPaint gp = new GradientPaint(pt1, color1, pt2, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, w, h);
        }
    
    }
    class jPanelTrasnparente extends JPanel{
        
        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            // Establecer el color de fondo con una transparencia
            g.setColor(new Color(255, 255, 255, 125)); // Color blanco con una opacidad del 50%
            g.fillRect(0, 0, getWidth(), getHeight());
        }  
    }
    public void mostrarDatosUsuarios(){
        CRUDOperation CRUDObject = new CRUDOperation();
        tabUsers.setModel(CRUDObject.mostrarUsuarios());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        jPanel2 = new jPanelTrasnparente();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabUsers = new javax.swing.JTable();
        txtNameUsr = new javax.swing.JTextField();
        btnEditarUsr = new javax.swing.JButton();
        btnCrearUsr = new javax.swing.JButton();
        btnRecargarTbl = new javax.swing.JButton();
        btnBorrarUsr = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setToolTipText("");

        tabUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabUsers);

        txtNameUsr.setEditable(false);
        txtNameUsr.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNameUsr.setForeground(new java.awt.Color(255, 255, 255));
        txtNameUsr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNameUsr.setText("jTextField1");
        txtNameUsr.setToolTipText("");
        txtNameUsr.setCaretColor(new java.awt.Color(60, 63, 65));
        txtNameUsr.setEnabled(false);
        txtNameUsr.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        btnEditarUsr.setBackground(new java.awt.Color(255, 215, 0));
        btnEditarUsr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnEditarUsr.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarUsr.setText("Editar usuario");
        btnEditarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsrActionPerformed(evt);
            }
        });

        btnCrearUsr.setBackground(new java.awt.Color(255, 215, 0));
        btnCrearUsr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCrearUsr.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearUsr.setText("Crear usuario");
        btnCrearUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsrActionPerformed(evt);
            }
        });

        btnRecargarTbl.setBackground(new java.awt.Color(255, 215, 0));
        btnRecargarTbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnRecargarTbl.setForeground(new java.awt.Color(0, 0, 0));
        btnRecargarTbl.setText("Recargar tabla");
        btnRecargarTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarTblActionPerformed(evt);
            }
        });

        btnBorrarUsr.setBackground(new java.awt.Color(255, 215, 0));
        btnBorrarUsr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBorrarUsr.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrarUsr.setText("Borrar usuario");
        btnBorrarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUsrActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 215, 0));
        btnSalir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CRUD - Panel Admin: ");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNameUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditarUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecargarTbl, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(btnBorrarUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNameUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnEditarUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnBorrarUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRecargarTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1245, 919));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsrActionPerformed
        

    }//GEN-LAST:event_btnEditarUsrActionPerformed

    private void btnCrearUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearUsrActionPerformed

    private void btnRecargarTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarTblActionPerformed
        mostrarDatosUsuarios();
    }//GEN-LAST:event_btnRecargarTblActionPerformed

    private void btnBorrarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarUsrActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    
    private void pintarLogo(JLabel lbl, String path){
        this.imagen = new ImageIcon(path);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        225,
                        252,
                        Image.SCALE_DEFAULT
                )
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        
        this.txtNameUsr.setText(usr.getUsername());
        //cargarTabla();
    }  
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarUsr;
    private javax.swing.JButton btnCrearUsr;
    private javax.swing.JButton btnEditarUsr;
    private javax.swing.JButton btnRecargarTbl;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tabUsers;
    private javax.swing.JTextField txtNameUsr;
    // End of variables declaration//GEN-END:variables
}
